name=input("enter the name:")
sem=int(input("enter your sem:"))
city=input("enter your city:")
pincode=int(input("enter your pincode:"))
print("/n/n/n")
print("student name:",name)
print("semester:",sem)
print("city:",city)
print("pincode:",pincode)